apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: rds
build:
  artifacts:
  - image: sjarosz/rcs
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
